export const REQUEST_KITTENS = 'REQUEST_KITTENS';
export const REQUEST_KITTENS_SUCCESS = 'REQUEST_KITTENS_SUCCESS';
export const REQUEST_KITTENS_ERROR = 'REQUEST_KITTENS_ERROR';

export const ADD_KITTEN = 'ADD_KITTEN';
export const ADD_KITTEN_SUCCESS = 'ADD_KITTEN_SUCCESS';
export const ADD_KITTEN_ERROR = 'ADD_KITTEN_ERROR';

export const DELETE_KITTEN = 'DELETE_KITTEN';
export const DELETE_KITTEN_SUCCESS = 'DELETE_KITTEN_SUCCESS';
export const DELETE_KITTEN_ERROR = 'DELETE_KITTEN_ERROR';
